(function(g){var window=this;var HCa=function(a,b){return g.Xb(a,b)},m6=function(a){g.Pm(a,"zx",g.yb());
return a},n6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Sm(a.o,b,c)},ICa=function(a,b){var c=[];
g.Dk(b,function(a){try{var b=g.oD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.v(b)?g.nD(b)&&c.push(a):c.push(a)},a);
return c},JCa=function(a,b){var c=ICa(a,b);
(0,g.C)(c,function(a){g.oD.prototype.remove.call(this,a)},a)},KCa=function(a){if(a.Fd){if(a.Fd.locationOverrideToken)return{locationOverrideToken:a.Fd.locationOverrideToken};
if(null!=a.Fd.latitudeE7&&null!=a.Fd.longitudeE7)return{latitudeE7:a.Fd.latitudeE7,longitudeE7:a.Fd.longitudeE7}}return null},LCa=function(a,b,c,d){var e=new g.Gm(null,void 0);
a&&g.Hm(e,a);b&&g.Im(e,b);c&&g.Jm(e,c);d&&g.Km(e,d);return e},MCa=function(a){g.dG[a]&&(a=g.dG[a],(0,g.C)(a,function(a){g.bG[a]&&delete g.bG[a]}),a.length=0)},NCa=function(a){var b=g.aG();
if(b)if(b.clear(a),a)MCa(a);else for(var c in g.dG)MCa(c)},o6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Am;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",OCa(this,a.capabilities||""),PCa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},OCa=function(a,b){a.capabilities.clear();
(0,g.Sd)(b.split(","),g.Fa(HCa,QCa)).forEach(function(b){a.capabilities.add(b)})},PCa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},p6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},q6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},RCa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},SCa=function(a){return new p6(a)},TCa=function(a){return g.za(a)?(0,g.I)(a,SCa):[]},r6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},s6=function(a){return g.za(a)?"["+(0,g.I)(a,r6).join(",")+"]":"null"},t6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},UCa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},u6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},v6=function(a,b){return g.La(a,function(a){return q6(a,b)})},VCa=function(){var a=(0,g.$G)();
a&&JCa(a,a.o.Yd(!0))},w6=function(){var a=g.cH("yt-remote-connected-devices")||[];
g.gb(a);return a},WCa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},XCa=function(a){g.bH("yt-remote-connected-devices",a,86400)},y6=function(){if(x6)return x6;
var a=g.cH("yt-remote-device-id");a||(a=t6(),g.bH("yt-remote-device-id",a,31536E3));for(var b=w6(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return x6=d},z6=function(){var a=w6(),b=y6();
g.Pa(a,b);g.eH()&&g.kb(a,b);a=WCa(a);if(g.Qa(a))try{g.MG("remote_sid")}catch(c){}else try{g.LG("remote_sid",a.join(","),-1)}catch(c){}},YCa=function(){return g.cH("yt-remote-session-browser-channel")},ZCa=function(){return g.cH("yt-remote-local-screens")||[]},$Ca=function(){g.bH("yt-remote-lounge-token-expiration",!0,86400)},aDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(ZCa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.om)(c,function(a){return!g.Pa(b,a)})&&$Ca();
g.bH("yt-remote-local-screens",a,31536E3)},bDa=function(a,b){g.bH("yt-remote-session-browser-channel",a);
g.bH("yt-remote-session-screen-id",b);var c=w6(),d=y6();g.Pa(c,d)||c.push(d);XCa(c);z6()},A6=function(a){a||(g.dH("yt-remote-session-screen-id"),g.dH("yt-remote-session-video-id"));
z6();a=w6();g.Ua(a,y6());XCa(a)},cDa=function(){if(!B6){var a=g.zD();
a&&(B6=new g.iD(a))}return B6?!!B6.get("yt-remote-use-staging-server"):!1},dDa=function(){var a=window.document.createElement("a");
g.gd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Cb(a)},eDa=function(a,b){var c=g.Ld("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.hd(c,g.je("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},fDa=function(){var a=dDa(),b=window.document.getElementById(a),c=b&&g.lF(b,"loaded");
c||b&&!c||(b=eDa(a,function(){g.lF(b,"loaded")||(g.kF(b,"loaded","true"),g.hG(a),g.hE(g.Fa(NCa,a),0))}))},C6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},gDa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},D6=function(a){a.length?hDa(a.shift(),function(){D6(a)}):E6()},iDa=function(a){return"chrome-extension://"+a+F6},hDa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},G6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},E6=function(){var a=gDa();
a&&a(!1,"No cast extension found")},H6=function(){if(jDa){var a=2,b=gDa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;hDa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",E6,c)}},kDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(H6(),a({command:"cast.sender.init"}))},lDa=function(){H6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);D6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+F6,"//www.gstatic.com/eureka/clank"+F6])},I6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.xd=b;this.D=(0,g.A)(this.QK,this);this.o=!1;this.A=0;this.B=this.Ea=null;this.C=[]},J6=function(){},K6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.Wm(this);this.A=new g.Ag;this.A.setInterval(250)},nDa=function(a,b,c){a.ck=1;
a.Bh=m6(b.clone());a.hj=c;a.D=!0;mDa(a,null)},L6=function(a,b,c,d,e){a.ck=1;
a.Bh=m6(b.clone());a.hj=null;a.D=c;e&&(a.RE=!1);mDa(a,d)},mDa=function(a,b){a.Rk=(0,g.G)();
M6(a);a.ci=a.Bh.clone();n6(a.ci,"t",a.F);a.sn=0;a.Qc=a.o.ws(a.o.cn()?b:null);0<a.ht&&(a.tq=new g.fl((0,g.A)(a.gG,a,a.Qc),a.ht));a.Y.W(a.Qc,"readystatechange",a.kW);var c=a.Fi?g.ec(a.Fi):{};a.hj?(a.lr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Qc.send(a.ci,a.lr,a.hj,c)):(a.lr="GET",a.RE&&!g.Hd&&(c.Connection="close"),a.Qc.send(a.ci,a.lr,null,c));a.o.Ef(1)},qDa=function(a,b,c){for(var d=!0;!a.ri&&a.sn<c.length;){var e=oDa(a,c);
if(e==N6){4==b&&(a.Ch=4,O6(15),d=!1);break}else if(e==pDa){a.Ch=4;O6(16);d=!1;break}else P6(a,e)}4==b&&0==c.length&&(a.Ch=1,O6(17),d=!1);a.Kf=a.Kf&&d;d||(Q6(a),R6(a))},oDa=function(a,b){var c=a.sn,d=b.indexOf("\n",c);
if(-1==d)return N6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return pDa;d+=1;if(d+c>b.length)return N6;var e=b.substr(d,c);a.sn=d+c;return e},sDa=function(a,b){a.Rk=(0,g.G)();
M6(a);var c=b?window.location.hostname:"";a.ci=a.Bh.clone();g.Pm(a.ci,"DOMAIN",c);g.Pm(a.ci,"t",a.F);try{a.Lf=new window.ActiveXObject("htmlfile")}catch(n){Q6(a);a.Ch=7;O6(22);R6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in S6)k=S6[l];else if(l in rDa)k=S6[l]=rDa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=S6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.id(g.Bc("b/12014412"),d+"</body></html>");a.Lf.open();a.Lf.write(g.$c(c));a.Lf.close();a.Lf.parentWindow.m=(0,g.A)(a.sV,a);a.Lf.parentWindow.d=(0,g.A)(a.ZD,a,!0);a.Lf.parentWindow.rpcClose=(0,g.A)(a.ZD,a,!1);c=a.Lf.createElement("DIV");a.Lf.parentWindow.document.body.appendChild(c);d=g.Pc(a.ci.toString());d=g.sb(g.Mc(d));d=g.id(g.Bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.fd(c,g.$c(d));a.o.Ef(1)},
M6=function(a){a.Ow=(0,g.G)()+a.C;
tDa(a,a.C)},tDa=function(a,b){if(null!=a.ll)throw Error("WatchDog timer not null");
a.ll=T6((0,g.A)(a.JV,a),b)},U6=function(a){a.ll&&(g.x.clearTimeout(a.ll),a.ll=null)},R6=function(a){a.o.cA()||a.ri||a.o.cq(a)},Q6=function(a){U6(a);
g.jf(a.tq);a.tq=null;a.A.stop();g.bn(a.Y);if(a.Qc){var b=a.Qc;a.Qc=null;b.abort();b.dispose()}a.Lf&&(a.Lf=null)},P6=function(a,b){try{a.o.RD(a,b),a.o.Ef(4)}catch(c){}},vDa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;uDa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){vDa(a,b,c,d,f)},f)})}},uDa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{V6(d),c(!0)}catch(e){}};
d.onerror=function(){try{V6(d),c(!1)}catch(e){}};
d.onabort=function(){try{V6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{V6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},V6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},wDa=function(a){this.o=a;
this.A=new J6},xDa=function(a){var b=W6(a.o,a.ul,"/mail/images/cleardot.gif");
m6(b);vDa(b.toString(),5E3,(0,g.A)(a.UJ,a),3,2E3);a.Ef(1)},Y6=function(a){var b=a.o.I;
if(null!=b)O6(5),b?(O6(11),X6(a.o,a,!1)):(O6(12),X6(a.o,a,!0));else if(a.Be=new K6(a,void 0,void 0,void 0),a.Be.Fi=a.Zs,b=a.o,b=W6(b,b.cn()?a.Wl:null,a.gt),O6(5),!g.Fd||g.tc(10))n6(b,"TYPE","xmlhttp"),L6(a.Be,b,!1,a.Wl,!1);else{n6(b,"TYPE","html");var c=a.Be;a=!!a.Wl;c.ck=3;c.Bh=m6(b.clone());sDa(c,a)}},Z6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new J6;this.H=a||null;this.I=null!=b?b:null;this.F=c||!1},yDa=function(a,b){this.o=a;
this.map=b;this.context=null},zDa=function(a){g.lf.call(this,"statevent",a)},ADa=function(a,b){g.lf.call(this,"timingevent",a);
this.size=b},BDa=function(a){g.lf.call(this,"serverreachability",a)},EDa=function(a){CDa(a);
if(3==a.o){var b=a.Lm++,c=a.Jo.clone();g.Pm(c,"SID",a.B);g.Pm(c,"RID",b);g.Pm(c,"TYPE","terminate");$6(a,c);b=new K6(a,a.B,b,void 0);b.ck=2;b.Bh=m6(c.clone());(new window.Image).src=b.Bh;b.Rk=(0,g.G)();M6(b)}DDa(a)},FDa=function(a){a.qK(1,0);
a.Jo=W6(a,null,a.Ys);a7(a)},CDa=function(a){a.oh&&(a.oh.abort(),a.oh=null);
a.yc&&(a.yc.cancel(),a.yc=null);a.xg&&(g.x.clearTimeout(a.xg),a.xg=null);b7(a);a.de&&(a.de.cancel(),a.de=null);a.th&&(g.x.clearTimeout(a.th),a.th=null)},GDa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new yDa(a.gR++,b));2!=a.o&&3!=a.o||a7(a)},a7=function(a){a.de||a.th||(a.th=T6((0,g.A)(a.XD,a),0),a.Rj=0)},IDa=function(a,b){if(1==a.o){if(!b){a.Lm=Math.floor(1E5*Math.random());
var c=a.Lm++,d=new K6(a,"",c,void 0);d.Fi=null;var e=c7(a),f=a.Jo.clone();g.Pm(f,"RID",c);g.Pm(f,"CVER","1");$6(a,f);nDa(d,f,e);a.de=d;a.o=2}}else 3==a.o&&(b?HDa(a,b):0==a.A.length||a.de||HDa(a))},HDa=function(a,b){if(b)if(6<a.ti){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Lm-1;var d=c7(a)}else c=b.G,d=b.hj;else c=a.Lm++,d=c7(a);var e=a.Jo.clone();g.Pm(e,"SID",a.B);g.Pm(e,"RID",c);g.Pm(e,"AID",a.rk);$6(a,e);c=new K6(a,a.B,c,a.Rj+1);c.Fi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.de=c;nDa(c,e,d)},$6=function(a,b){if(a.wd){var c=a.wd.Jz();
c&&g.Kb(c,function(a,c){g.Pm(b,c,a)})}},c7=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.ti&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.ti?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},JDa=function(a){a.yc||a.xg||(a.G=1,a.xg=T6((0,g.A)(a.WD,a),0),a.Dj=0)},d7=function(a){if(a.yc||a.xg||3<=a.Dj)return!1;
a.G++;a.xg=T6((0,g.A)(a.WD,a),KDa(a,a.Dj));a.Dj++;return!0},X6=function(a,b,c){a.kr=c;
a.Zf=b.Ig;a.F||FDa(a)},b7=function(a){null!=a.wi&&(g.x.clearTimeout(a.wi),a.wi=null)},KDa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},e7=function(a,b){if(2==b||9==b){var c=null;
a.wd&&(c=null);var d=(0,g.A)(a.fX,a);c||(c=new g.Gm("//www.google.com/images/cleardot.gif"),m6(c));uDa(c.toString(),1E4,d)}else O6(2);LDa(a,b)},LDa=function(a,b){a.o=0;
a.wd&&a.wd.Iy(b);DDa(a);CDa(a)},DDa=function(a){a.o=0;
a.Zf=-1;if(a.wd)if(0==a.C.length&&0==a.A.length)a.wd.ds();else{g.Ya(a.C);var b=g.Ya(a.A);a.C.length=0;a.A.length=0;a.wd.ds(b)}},W6=function(a,b,c){var d=g.Qm(c);
if(""!=d.A)b&&g.Im(d,b+"."+d.A),g.Jm(d,d.D);else{var e=window.location;d=LCa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Gl&&g.Kb(a.Gl,function(a,b){g.Pm(d,b,a)});
g.Pm(d,"VER",a.ti);$6(a,d);return d},T6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},O6=function(a){f7.dispatchEvent(new zDa(f7,a))},MDa=function(){},NDa=function(a,b){this.action=a;
this.params=b||{}},g7=function(a,b){g.M.call(this);
this.o=new g.ju(this.jV,0,this);g.N(this,this.o);this.xd=5E3;this.A=0;if(g.Ba(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},h7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.hD;this.A=new g7(this.PX,this);this.o=this.gb=null;this.K=!1;this.D=null;this.I="";this.H=this.C=0;this.G=[];this.M=c||!1},ODa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.kr,sessionId:a.o.B,arrayId:a.o.rk}},PDa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&IDa(a.o),EDa(a.o));a.H=0},i7=function(a){return!!a.o&&3==a.o.o},QDa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},j7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Qg(a)||"";b&&(this.port=":"+b);this.domain=g.Pg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Bb(a,"10.0")&&(this.A=!1))},k7=function(a,b){var c=a.o;
if(g.v(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.Zg(c+b,{})},l7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.C,d,!0),onError:g.Fa(a.B,e),Cd:g.Fa(a.D,e)};c&&(a.Pb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.yE(b,a)},UDa=function(){var a=RDa;
SDa();m7.push(a);TDa(m7)},n7=function(a,b){SDa();
var c=m7,d=VDa(a,String(b));g.Qa(c)?WDa(d):(TDa(c),(0,g.C)(c,function(a){a(d)}))},SDa=function(){m7||(m7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",m7,void 0))},WDa=function(a){var b=(o7+1)%50;
o7=b;p7[b]=a;q7||(q7=49==b)},TDa=function(a){var b=p7;
if(b[0]){var c=o7,d=q7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
p7=Array(50);o7=-1;q7=!1}},VDa=function(a,b){var c=((0,g.G)()-XDa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},r7=function(a){g.TF.call(this);
this.G=a;this.o=[]},YDa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},ZDa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Sd)(a.o,function(a){return!!u6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=YDa(a,b[d])||c;return c},$Da=function(a,b){var c=a.o.length;
a.o=(0,g.Sd)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},s7=function(a,b,c,d){g.TF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ea=window.NaN},u7=function(a){r7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;t7(this);this.info("Initializing with "+s6(this.o))},aEa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=k7(a.B,"/pairing/get_lounge_token_batch");
l7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.dL,a),(0,g.A)(a.cL,a))}},t7=function(a){var b=TCa(ZCa());
b=(0,g.Sd)(b,function(a){return!a.uuid});
return ZDa(a,b)},v7=function(a,b){aDa((0,g.I)(a.o,RCa));
b&&$Ca()},x7=function(a,b){g.TF.call(this);
this.F=b;var c=g.cH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;w7("Initialized with "+g.Hg(this.o))},bEa=function(a,b,c){var d=k7(a.D,"/pairing/get_screen_availability");
l7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},y7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.o))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(w7("Updated online screens: "+g.Hg(a.o)),a.o=b,a.V("screenChange"));cEa(a)},z7=function(a){(0,window.isNaN)(a.B)||g.jE(a.B);
a.B=g.hE((0,g.A)(a.Xv,a),0<a.C&&a.C<(0,g.G)()?2E4:1E4)},w7=function(a){n7("OnlineScreenService",a)},dEa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.hc("Requesting availability of screen w/o lounge token.")});
return b},cEa=function(a){a=g.Sb(g.Lb(a.o,function(a){return a}));
g.gb(a);a.length?g.bH("yt-remote-online-screen-ids",a.join(","),60):g.dH("yt-remote-online-screen-ids")},A7=function(a){r7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};eEa(this)},gEa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.te();if(k=(c?v6(k,c):null)||v6(k,b)){k.uuid=b;var l=B7(a,k);bEa(a.A,l,function(a){e(a?l:null)})}else c?fEa(a,c,(0,g.A)(function(a){var f=B7(this,new p6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));bEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},hEa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},fEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Pb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.yE(k7(a.F,"/pairing/get_lounge_token_batch"),e)},iEa=function(a){a.o=a.B.te();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+s6(a.o))},eEa=function(a){C7(a);
a.B=new u7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.sL,a));iEa(a);a.C=TCa(g.cH("yt-remote-automatic-screen-cache")||[]);C7(a);a.info("Initializing automatic screens: "+s6(a.C));a.A=new x7(a.F,(0,g.A)(a.te,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},B7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=v6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.bH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,RCa)));C7(a);a.D[b.uuid]=b.id;g.bH("yt-remote-device-id-map",a.D,31536E3);return b},C7=function(a){a.D=g.cH("yt-remote-device-id-map")||{}},D7=function(a,b,c){g.TF.call(this);
this.M=c;this.I=a;this.A=b;this.B=null},E7=function(a,b){n7(a.M,b)},F7=function(a,b){D7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.VX,this);this.D=(0,g.A)(this.VV,this);this.C=g.hE((0,g.A)(function(){jEa(this,null)},this),12E4)},kEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Hg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){E7(this,"Failed to send message: getMdxSessionStatus.")},a)):E7(a,"Sending yt message without session: "+g.Hg(b))},jEa=function(a,b){g.jE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.eq,a),d=(0,g.A)(a.ze,a);a.Tz(b,c,d,5)}}else a.ze(Error("Waiting for session status timed out."))},G7=function(a,b,c){D7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.z;this.F=window.NaN;this.L=(0,g.A)(this.YX,this);this.o=g.z},lEa=function(a){a.o=a.I.nG(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.eq(a)},a),(0,g.A)(function(a){this.o=g.z;
this.ze(a)},a))},mEa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}cDa()&&(b.env_useStageMdx=1);return g.Xg(b)},H7=function(a,b){D7.call(this,a,b,"ManualSession");
this.o=g.hE((0,g.A)(this.tk,this,null),150)},I7=function(a,b,c,d){g.TF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.wU,this)},nEa=function(a,b){return b?g.La(a.B,function(a){return q6(b,a.label)},a):null},J7=function(a){n7("Controller",a)},RDa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},K7=function(a){return a.D||!!a.B.length||!!a.o},L7=function(a,b,c){b!=a.o&&(g.jf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.UD,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.tk(null)):a.V("yt-remote-cast2-session-change",null))},oEa=function(a){var b=a.A.mG(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&q6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=nEa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},uEa=function(a,b,c,d,e,f,k){pEa()?qEa(b,e,f,k)&&(N7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?rEa(a,c):(window.__onGCastApiAvailable=function(b,d){b?rEa(a,c):(O7("Failed to load cast API: "+d),P7(!1),N7(!1),g.dH("yt-remote-cast-available"),g.dH("yt-remote-cast-receiver"),sEa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):fDa():G6("CriOS")?kDa():G6("Android")&&G6("Chrome/")&&window.navigator.presentation?lDa():window.chrome&&window.navigator.presentation&&!G6("Edge")?(H6(),D6(tEa.map(iDa))):E6())):M7("Cannot initialize because not running Chrome")},sEa=function(){M7("dispose");
var a=Q7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);vEa(!1);g.fG(R7);R7.length=0},S7=function(){return!!g.cH("yt-remote-cast-installed")},wEa=function(){var a=g.cH("yt-remote-cast-receiver");
return a?a.friendlyName:null},xEa=function(){M7("clearCurrentReceiver");
g.dH("yt-remote-cast-receiver")},yEa=function(){return S7()?Q7()?Q7().getCastSession():(O7("getCastSelector: Cast is not initialized."),null):(O7("getCastSelector: Cast API is not installed!"),null)},U7=function(){S7()?Q7()?T7()?(M7("Requesting cast selector."),Q7().requestSession()):(M7("Wait for cast API to be ready to request the session."),R7.push(g.eG("yt-remote-cast2-api-ready",U7))):O7("requestCastSelector: Cast is not initialized."):O7("requestCastSelector: Cast API is not installed!")},V7=
function(a,b){T7()?Q7().setConnectedScreenStatus(a,b):O7("setConnectedScreenStatus called before ready.")},pEa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.QI||a},zEa=function(a,b){Q7().init(a,b)},qEa=function(a,b,c,d){var e=!1;
Q7()||(a=new I7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.bH("yt-remote-cast-available",a);g.iG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){M7("onReceiverSelected: "+a.friendlyName);
g.bH("yt-remote-cast-receiver",a);g.iG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){M7("onReceiverResumed: "+a.friendlyName);
g.bH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){M7("onSessionChange: "+r6(a));
a||g.dH("yt-remote-cast-receiver");g.iG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
M7("cloudview.createSingleton_: "+e);return e},Q7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},rEa=function(a,b){P7(!0);
N7(!1);zEa(a,function(a){a?(vEa(!0),g.hG("yt-remote-cast2-api-ready")):(O7("Failed to initialize cast API."),P7(!1),g.dH("yt-remote-cast-available"),g.dH("yt-remote-cast-receiver"),sEa());b(a)})},M7=function(a){n7("cloudview",a)},O7=function(a){n7("cloudview",a)},P7=function(a){M7("setCastInstalled_ "+a);
g.bH("yt-remote-cast-installed",a)},T7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},vEa=function(a){M7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},N7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},W7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.eg=!1;this.K=this.I=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},X7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.eg=!1;a.hasNext=!1;a.H=0;a.G=(0,g.G)();a.D=0;a.B=0;a.I=0;a.K=0;a.C=window.NaN;a.F=!1},Y7=function(a){return a.qb()?((0,g.G)()-a.G)/1E3:0},Z7=function(a,b){a.H=b;
a.G=(0,g.G)()},$7=function(a){switch(a.o){case 1:case 1081:return((0,g.G)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},a8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&X7(a)},b8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.fc(a.A);b.hasPrevious=a.eg;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.I;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},d8=function(a,b){g.TF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.xC;this.B=this.A=null;this.I=(0,g.A)(this.QR,this);this.G=(0,g.A)(this.Om,this);this.H=(0,g.A)(this.PR,this);this.K=(0,g.A)(this.cS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Vw,this),AEa(this))):c=3;0!=c&&(b?this.Vw(c):g.hE((0,g.A)(function(){this.Vw(c)},this),0));
var d=yEa();d&&c8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},e8=function(a){return new W7(a.C.getPlayerContextData())},AEa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Fa(this.rU,a),this))},a)},BEa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},f8=function(a,b){50>a.D.zc()&&g.zC(a.D,b)},h8=function(a,b,c){var d=e8(a);
Z7(d,c);-1E3!=d.o&&(d.o=b);g8(a,d)},i8=function(a,b,c){a.C.sendMessage(b,c)},g8=function(a,b){BEa(a);
a.C.setPlayerContextData(b8(b));AEa(a)},c8=function(a,b){a.B&&(a.B.removeUpdateListener(a.I),a.B.removeMediaListener(a.G),a.Om(null));
a.B=b;a.B&&(n7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.I),a.B.addMediaListener(a.G),a.B.media.length&&a.Om(a.B.media[0]))},CEa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=e8(a);b.contentId!=d.videoId&&n7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;Z7(d,a.A.getEstimatedTime());g8(a,d)}else n7("CP","No cast media video. Ignoring state update.")},j8=function(a,b,c){return(0,g.A)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),i8(this,b,c))},a)},k8=function(a,b,c){g.TF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.I=this.L=this.M=window.NaN;this.T=[];this.C=this.G=this.B=this.ib=this.o=null;this.sa=a;this.T.push(g.CF(window,"beforeunload",(0,g.A)(this.UK,this)));this.A=[];this.ib=new W7;this.ba=b.id;this.o=DEa(this,c);this.o.subscribe("handlerOpened",this.UR,this);this.o.subscribe("handlerClosed",this.RR,this);this.o.subscribe("handlerError",this.SR,this);this.o.subscribe("handlerMessage",this.TR,this);QDa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.ib.videoId;g.eH()&&g.bH("yt-remote-session-video-id",a)},this)},l8=function(a){n7("conn",a)},DEa=function(a,b){return new h7(k7(a.sa,"/bc"),b)},m8=function(a,b){a.V("proxyStateChange",b)},EEa=function(a){a.D=g.hE((0,g.A)(function(){l8("Connecting timeout");
this.F(1)},a),2E4)},n8=function(a){g.jE(a.D);
a.D=window.NaN},o8=function(a){g.jE(a.M);
a.M=window.NaN},FEa=function(a){p8(a);
a.L=g.hE((0,g.A)(function(){q8(this,"getNowPlaying")},a),2E4)},p8=function(a){g.jE(a.L);
a.L=window.NaN},HEa=function(a,b){b&&(n8(a),o8(a));
b==(i7(a.o)&&(0,window.isNaN)(a.D))?b&&(m8(a,1),q8(a,"getSubtitlesTrack")):b?(a.Z()&&a.ib.reset(),m8(a,1),q8(a,"getNowPlaying"),GEa(a)):a.F(1)},IEa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ib.videoId&&(g.$b(b.params)?a.ib.A=null:a.ib.A=b.params,a.V("remotePlayerChange"))},JEa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.ib.listId=b.params.listId||a.ib.listId;a8(a.ib,c,d);a.V("remoteQueueChange")},LEa=function(a,b){b.params=b.params||{};
JEa(a,b);KEa(a,b);a.V("autoplayDismissed")},KEa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
Z7(a.ib,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.ib.o&&(c=-1E3);a.ib.o=c;c=Number(b.params.loadedTime);a.ib.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.ib.I=(0,window.isNaN)(c)?0:c;c=a.ib;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.ib.o?FEa(a):p8(a);
a.V("remotePlayerChange")},MEa=function(a,b){if(-1E3!=a.ib.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ib.o=c;c=(0,window.parseInt)(b.params.currentTime,10);Z7(a.ib,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},NEa=function(a,b){var c="true"==b.params.muted;
a.ib.volume=(0,window.parseInt)(b.params.volume,10);a.ib.muted=c;a.V("remotePlayerChange")},OEa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},PEa=function(a,b){var c="true"==b.params.hasNext;
a.ib.eg="true"==b.params.hasPrevious;a.ib.hasNext=c;a.V("previousNextChange")},GEa=function(a){g.jE(a.K);
a.K=g.hE((0,g.A)(a.F,a,1),864E5)},q8=function(a,b,c){c?l8("Sending: action="+b+", params="+g.Hg(c)):l8("Sending: action="+b);
a.o.sendMessage(b,c)},r8=function(a){r7.call(this,"ScreenServiceProxy");
this.gd=a;this.A=[];this.A.push(this.gd.$_s("screenChange",(0,g.A)(this.TX,this)));this.A.push(this.gd.$_s("onlineScreenChange",(0,g.A)(this.QT,this)))},UEa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.bE("MDX_CONFIG")||b;VCa();z6();s8||(s8=new j7(b?b.loungeApiHost:void 0),cDa()&&(s8.o="/api/loungedev"));t8||(t8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",t8,void 0));QEa();var c=u8();if(!c){var d=new A7(s8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=u8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);uEa(a,d,function(a){a?v8()&&V7(v8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.iG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),w8("Initializing: "+g.Hg(b)),x8.push(g.eG("yt-remote-cast2-availability-change",function(){g.iG("yt-remote-receiver-availability-change")})),x8.push(g.eG("yt-remote-cast2-receiver-selected",function(){y8(null);
g.iG("yt-remote-auto-connect","cast-selector-receiver")})),x8.push(g.eG("yt-remote-cast2-receiver-resumed",function(){g.iG("yt-remote-receiver-resumed","cast-selector-receiver")})),x8.push(g.eG("yt-remote-cast2-session-change",REa)),x8.push(g.eG("yt-remote-connection-change",function(a){a?V7(v8(),"YouTube TV"):z8()||(V7(null,null),xEa())})),a=A8(),b.isAuto&&(a.id+="#dial"),g.ZF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),w8(" -- with channel params: "+
g.Hg(a)),SEa(a),c.start(),v8()||TEa())},WEa=function(){var a=VEa();
S7()&&g.cH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},VEa=function(){var a=u8().gd.$_gos();
var b=B8();b&&C8()&&(u6(a,b)||a.push(b));return UCa(a)},D8=function(){var a=XEa();
!a&&S7()&&wEa()&&(a={key:"cast-selector-receiver",name:wEa()});return a},XEa=function(){var a=VEa(),b=B8();
b||(b=z8());return g.La(a,function(a){return b&&q6(b,a.key)?!0:!1})},B8=function(){var a=v8();
if(!a)return null;var b=u8().te();return v6(b,a)},REa=function(a){w8("remote.onCastSessionChange_: "+r6(a));
if(a){var b=B8();b&&b.id==a.id?V7(b.id,"YouTube TV"):(b&&E8(),F8(a,1))}else C8()&&E8()},E8=function(){T7()?Q7().stopSession():O7("stopSession called before API ready.");
var a=C8();a&&(a.disconnect(1),G8(null))},H8=function(){var a=C8();
return!!a&&3!=a.getProxyState()},w8=function(a){n7("remote",a)},u8=function(){if(!I8){var a=g.y("yt.mdx.remote.screenService_");
I8=a?new r8(a):null}return I8},v8=function(){return g.y("yt.mdx.remote.currentScreenId_")},YEa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},ZEa=function(){return g.y("yt.mdx.remote.connectData_")},y8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},C8=function(){return g.y("yt.mdx.remote.connection_")},G8=function(a){var b=C8();
y8(null);a||YEa("");g.ua("yt.mdx.remote.connection_",a,void 0);t8&&((0,g.C)(t8,function(b){b(a)}),t8.length=0);
b&&!a?g.iG("yt-remote-connection-change",!1):!b&&a&&g.iG("yt-remote-connection-change",!0)},z8=function(){var a=g.eH();
if(!a)return null;var b=u8().te();return v6(b,a)},F8=function(a,b){B8()&&B8();
YEa(a.id);var c=new k8(s8,a,A8());c.connect(b,ZEa());c.subscribe("beforeDisconnect",function(a){g.iG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){C8()&&G8(null)});
G8(c)},TEa=function(){var a=z8();
a?(w8("Resume connection to: "+r6(a)),F8(a,0)):(A6(),xEa(),w8("Skipping connecting because no session screen found."))},QEa=function(){var a=A8();
if(g.$b(a)){a=y6();var b=g.cH("yt-remote-session-name")||"",c=g.cH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},A8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},SEa=function(a){a?(g.bH("yt-remote-session-app",a.app),g.bH("yt-remote-session-name",a.name)):(g.dH("yt-remote-session-app"),g.dH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},J8=function(a,b,c){g.M.call(this);
this.H=a;this.A=b;this.B=new g.QF(this);g.N(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.jT);this.B.R(b,"captionschanged",this.OR);this.B.R(b,"captionssettingschanged",this.AF);this.B.R(b,"videoplayerreset",this.fq);this.B.R(b,"mdxautoplaycancel",this.TJ);this.T=this.B.R(b,"onVolumeChange",this.CD);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.QD,this);c.subscribe("remotePlayerChange",this.Rm,this);c.subscribe("remoteQueueChange",this.fq,this);c.subscribe("autoplayUpNext",this.nD,
this);c.subscribe("previousNextChange",this.ND,this);c.subscribe("nowAutoplaying",this.ED,this);c.subscribe("autoplayDismissed",this.mD,this);this.suggestion=null;this.I=new g.HP(64);this.C=new g.ju(this.wF,500,this);g.N(this,this.C);this.D=new g.ju(this.xF,1E3,this);g.N(this,this.D);this.L=new I6(this.uX,0,this);g.N(this,this.L);this.F={};this.M=new g.ju(this.WF,1E3,this);g.N(this,this.M);this.K=new g.fl(this.OP,1E3,this);g.N(this,this.K);this.O=g.z;this.AF();this.fq();this.Rm()},K8=function(a,b){var c=
a.H,d=a.A.getVideoData().lengthSeconds;
c.I=b||0;c.o.V("progresssync",b,d)},$Ea=function(a){K8(a,0);
a.C.stop();L8(a,new g.HP(64))},N8=function(a,b){if(M8(a)&&!a.G){var c=null;
b&&(c={style:a.A.aj()},g.hc(c,b));a.o.lF(a.A.getVideoData(1).videoId,c);a.F=e8(a.o).A}},O8=function(a,b){var c=a.A.mg();
if(c){var d=c.re();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.lk;f=KCa(f);var n=e8(c);l=l||0;var p={videoId:k,currentIndex:l};a8(n,k,l);g.v(b)&&(Z7(n,b),p.currentTime=b);g.v(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Hg(f));i8(c,"setPlaylist",p);e||g8(c,n);L8(a,new g.HP(1))},aFa=function(a,b){if(b){var c=a.A.Cc("captions","tracklist",{NA:1});
c&&c.length?(a.A.Sd("captions","track",b),a.G=!1):(a.A.Ak("captions"),a.G=!0)}else a.A.Sd("captions","track",{})},M8=function(a){return e8(a.o).videoId==a.A.getVideoData(1).videoId},L8=function(a,b){a.D.stop();
var c=a.I;if(!g.MP(c,b)){var d=g.X(b,2);d!=g.X(a.I,2)&&g.dU(a.A,d);a.I=b;bFa(a.H,c,b)}},P8=function(a){g.W.call(this,{J:"div",
N:"ytp-remote",P:[{J:"div",N:"ytp-remote-display-status",P:[{J:"div",N:"ytp-remote-display-status-icon",P:[g.oqa()]},{J:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.A=new g.VU(this,250);g.N(this,this.A);this.C=a;this.R(a,"presentingplayerstatechange",this.D);cFa(this,g.aU(a))},cFa=function(a,b){if(3==a.C.Ra()){var c={RECEIVER_NAME:a.C.Cc("remote","currentReceiver").name};
c=g.X(b,128)?g.d0("Error on $RECEIVER_NAME",c):b.qb()||g.X(b,4)?g.d0("Playing on $RECEIVER_NAME",c):g.d0("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.A.show()}else a.A.hide()},Q8=function(a,b){g.eZ.call(this,"Play on",0,a,b);
this.A=a;this.I={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},R8=function(a){g.BU.call(this,a);
this.B={key:t6(),name:"This computer"};this.D=null;this.F=[];this.K=this.A=null;this.H=[this.B];this.C=this.B;this.G=new g.HP(64);this.I=0;if(!g.TM(g.Y(this.o))){a=this.o;var b=g.UH(a);b&&(b=b.Bp())&&(b=new Q8(a,b),g.N(this,b));b=new P8(a);g.N(this,b);g.tU(a,b.element,4)}},bFa=function(a,b,c){a.G=c;
a.o.V("presentingplayerstatechange",new g.RP(c,b))},S8=function(a,b){if(b.key!=a.C.key)if(b.key==a.B.key)E8();
else{a.C=b;var c=a.o.getPlaylistId();var d=a.o.getVideoData(1);var e=d.videoId;if(c||e){var f=a.o.mg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ac(l).videoId}else k=[e];f=a.o.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.lk,index:Math.max(a.o.SB(),0),currentTime:0==f?void 0:f};(d=KCa(d))&&(c.locationInfo=d);d=c}else d=null;w8("Connecting to: "+g.Hg(b));"cast-selector-receiver"==b.key?(y8(d||null),T7()?Q7().setLaunchParams(d||null):
O7("setLaunchParams called before ready.")):!d&&H8()&&v8()==b.key?g.iG("yt-remote-connection-change",!0):(E8(),y8(d||null),d=u8().te(),(d=v6(d,b.key))&&F8(d,1))}},rDa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},S6={"'":"\\'"},dFa={},QCa={iZ:"atp",N3:"ska",c3:"que",n2:"mus",J3:"sus",r0:"dsp"};
o6.prototype.qo=function(){var a=new o6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var B6,x6="",F6=C6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",jDa=C6("loadCastFramework")||C6("loadCastApplicationFramework"),tEa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(I6,g.M);g.h=I6.prototype;g.h.PK=function(a){this.C=arguments;this.o=!1;this.Ea?this.B=(0,g.G)()+this.xd:this.Ea=g.Bg(this.D,this.xd)};
g.h.stop=function(){this.Ea&&(g.Cg(this.Ea),this.Ea=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();I6.ea.X.call(this)};
g.h.QK=function(){this.B?(this.Ea=g.Bg(this.D,this.B-(0,g.G)()),this.B=null):(this.Ea=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};J6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
J6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=K6.prototype;g.h.Fi=null;g.h.Kf=!1;g.h.ll=null;g.h.Ow=null;g.h.Rk=null;g.h.ck=null;g.h.Bh=null;g.h.ci=null;g.h.hj=null;g.h.Qc=null;g.h.sn=0;g.h.Lf=null;g.h.lr=null;g.h.Ch=null;g.h.Xl=-1;g.h.RE=!0;g.h.ri=!1;g.h.ht=0;g.h.tq=null;var pDa={},N6={};g.h=K6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.kW=function(a){a=a.target;var b=this.tq;b&&3==g.tx(a)?b.ak():this.gG(a)};
g.h.gG=function(a){try{if(a==this.Qc)a:{var b=g.tx(this.Qc),c=this.Qc.A,d=this.Qc.getStatus();if(g.Fd&&!g.tc(10)||g.Hd&&!g.sc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.nf&&!g.xx(this.Qc))break a;this.ri||4!=b||7==c||(8==c||0>=d?this.o.Ef(3):this.o.Ef(2));U6(this);var e=this.Qc.getStatus();this.Xl=e;var f=g.xx(this.Qc);(this.Kf=200==e)?(4==b&&Q6(this),this.D?(qDa(this,b,f),g.nf&&this.Kf&&3==b&&(this.Y.W(this.A,"tick",this.gW),this.A.start())):P6(this,f),this.Kf&&!this.ri&&(4==b?this.o.cq(this):
(this.Kf=!1,M6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ch=3,O6(13)):(this.Ch=0,O6(14)),Q6(this),R6(this))}}catch(k){this.Qc&&g.xx(this.Qc)}finally{}};
g.h.gW=function(){var a=g.tx(this.Qc),b=g.xx(this.Qc);this.sn<b.length&&(U6(this),qDa(this,a,b),this.Kf&&4!=a&&M6(this))};
g.h.sV=function(a){T6((0,g.A)(this.rV,this,a),0)};
g.h.rV=function(a){this.ri||(U6(this),P6(this,a),M6(this))};
g.h.ZD=function(a){T6((0,g.A)(this.qV,this,a),0)};
g.h.qV=function(a){this.ri||(Q6(this),this.Kf=a,this.o.cq(this),this.o.Ef(4))};
g.h.cancel=function(){this.ri=!0;Q6(this)};
g.h.JV=function(){this.ll=null;var a=(0,g.G)();0<=a-this.Ow?(2!=this.ck&&this.o.Ef(3),Q6(this),this.Ch=2,O6(18),R6(this)):tDa(this,this.Ow-a)};g.h=wDa.prototype;g.h.Zs=null;g.h.Be=null;g.h.uq=!1;g.h.dA=null;g.h.Fo=null;g.h.hu=null;g.h.gt=null;g.h.Ve=null;g.h.Ig=-1;g.h.Wl=null;g.h.ul=null;g.h.connect=function(a){this.gt=a;a=W6(this.o,null,this.gt);O6(3);this.dA=(0,g.G)();var b=this.o.H;null!=b?(this.Wl=b[0],(this.ul=b[1])?(this.Ve=1,xDa(this)):(this.Ve=2,Y6(this))):(n6(a,"MODE","init"),this.Be=new K6(this,void 0,void 0,void 0),this.Be.Fi=this.Zs,L6(this.Be,a,!1,null,!0),this.Ve=0)};
g.h.UJ=function(a){if(a)this.Ve=2,Y6(this);else{O6(4);var b=this.o;b.Zf=b.oh.Ig;e7(b,9)}a&&this.Ef(2)};
g.h.ws=function(a){return this.o.ws(a)};
g.h.abort=function(){this.Be&&(this.Be.cancel(),this.Be=null);this.Ig=-1};
g.h.cA=function(){return!1};
g.h.RD=function(a,b){this.Ig=a.Xl;if(0==this.Ve)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Zf=this.Ig;e7(c,2);return}this.Wl=c[0];this.ul=c[1]}else c=this.o,c.Zf=this.Ig,e7(c,2);else if(2==this.Ve)if(this.uq)O6(7),this.hu=(0,g.G)();else if("11111"==b){if(O6(6),this.uq=!0,this.Fo=(0,g.G)(),c=this.Fo-this.dA,!g.Fd||g.tc(10)||500>c)this.Ig=200,this.Be.cancel(),O6(12),X6(this.o,this,!0)}else O6(8),this.Fo=this.hu=(0,g.G)(),this.uq=!1};
g.h.cq=function(){this.Ig=this.Be.Xl;if(this.Be.Kf)0==this.Ve?this.ul?(this.Ve=1,xDa(this)):(this.Ve=2,Y6(this)):2==this.Ve&&((!g.Fd||g.tc(10)?!this.uq:200>this.hu-this.Fo)?(O6(11),X6(this.o,this,!1)):(O6(12),X6(this.o,this,!0)));else{0==this.Ve?O6(9):2==this.Ve&&O6(10);var a=this.o;a.Zf=this.Ig;e7(a,2)}};
g.h.cn=function(){return this.o.cn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Ef=function(a){this.o.Ef(a)};g.h=Z6.prototype;g.h.Gl=null;g.h.de=null;g.h.yc=null;g.h.Ys=null;g.h.Jo=null;g.h.yy=null;g.h.Wo=null;g.h.Lm=0;g.h.gR=0;g.h.wd=null;g.h.th=null;g.h.xg=null;g.h.wi=null;g.h.oh=null;g.h.kr=null;g.h.rk=-1;g.h.dB=-1;g.h.Zf=-1;g.h.Rj=0;g.h.Dj=0;g.h.ti=8;var f7=new g.Mf;g.B(zDa,g.lf);g.B(ADa,g.lf);g.B(BDa,g.lf);g.h=Z6.prototype;g.h.connect=function(a,b,c,d,e){O6(0);this.Ys=b;this.Gl=c||{};d&&g.v(e)&&(this.Gl.OSID=d,this.Gl.OAID=e);this.F?(T6((0,g.A)(this.Ty,this,a),100),FDa(this)):this.Ty(a)};
g.h.Ty=function(a){this.oh=new wDa(this);this.oh.Zs=null;this.oh.A=this.D;this.oh.connect(a)};
g.h.cA=function(){return 0==this.o};
g.h.XD=function(a){this.th=null;IDa(this,a)};
g.h.WD=function(){this.xg=null;this.yc=new K6(this,this.B,"rpc",this.G);this.yc.Fi=null;this.yc.ht=0;var a=this.yy.clone();g.Pm(a,"RID","rpc");g.Pm(a,"SID",this.B);g.Pm(a,"CI",this.kr?"0":"1");g.Pm(a,"AID",this.rk);$6(this,a);if(!g.Fd||g.tc(10))g.Pm(a,"TYPE","xmlhttp"),L6(this.yc,a,!0,this.Wo,!1);else{g.Pm(a,"TYPE","html");var b=this.yc,c=!!this.Wo;b.ck=3;b.Bh=m6(a.clone());sDa(b,c)}};
g.h.RD=function(a,b){if(0!=this.o&&(this.yc==a||this.de==a))if(this.Zf=a.Xl,this.de==a&&3==this.o)if(7<this.ti){try{var c=this.D.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.xg){if(this.yc)if(this.yc.Rk+3E3<this.de.Rk)b7(this),this.yc.cancel(),this.yc=null;else break a;d7(this);O6(19)}}else this.dB=c[1],0<this.dB-this.rk&&37500>c[2]&&this.kr&&0==this.Dj&&!this.wi&&(this.wi=T6((0,g.A)(this.JR,this),6E3));else e7(this,11)}else b!=dFa.l_.o&&e7(this,11);else if(this.yc==a&&
b7(this),!g.D(b)){c=this.D.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.rk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Wo=e[2],e=e[3],null!=e?this.ti=e:this.ti=6,this.o=3,this.wd&&this.wd.Ky(),this.yy=W6(this,this.cn()?this.Wo:null,this.Ys),JDa(this)):"stop"==e[0]&&e7(this,7):3==this.o&&("stop"==e[0]?e7(this,7):"noop"!=e[0]&&this.wd&&this.wd.Jy(e),this.Dj=0)}}};
g.h.JR=function(){null!=this.wi&&(this.wi=null,this.yc.cancel(),this.yc=null,d7(this),O6(20))};
g.h.cq=function(a){if(this.yc==a){b7(this);this.yc=null;var b=2}else if(this.de==a)this.de=null,b=1;else return;this.Zf=a.Xl;if(0!=this.o)if(a.Kf)1==b?(b=(0,g.G)()-a.Rk,f7.dispatchEvent(new ADa(f7,a.hj?a.hj.length:0,b,this.Rj)),a7(this),this.C.length=0):JDa(this);else{var c=a.Ch,d;if(!(d=3==c||7==c||0==c&&0<this.Zf)){if(d=1==b)this.de||this.th||1==this.o||2<=this.Rj?d=!1:(this.th=T6((0,g.A)(this.XD,this,a),KDa(this,this.Rj)),this.Rj++,d=!0);d=!(d||2==b&&d7(this))}if(d)switch(c){case 1:e7(this,5);
break;case 4:e7(this,10);break;case 3:e7(this,6);break;case 7:e7(this,12);break;default:e7(this,2)}}};
g.h.qK=function(a){if(!g.Pa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.fX=function(a){a?O6(2):(O6(1),LDa(this,8))};
g.h.ws=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.nx;a.H=!1;return a};
g.h.isActive=function(){return!!this.wd&&this.wd.isActive(this)};
g.h.Ef=function(a){f7.dispatchEvent(new BDa(f7,a))};
g.h.cn=function(){return!(!g.Fd||g.tc(10))};
g.h=MDa.prototype;g.h.Ky=function(){};
g.h.Jy=function(){};
g.h.Iy=function(){};
g.h.ds=function(){};
g.h.Jz=function(){return{}};
g.h.isActive=function(){return!0};g.B(g7,g.M);g.h=g7.prototype;g.h.jV=function(){this.xd=Math.min(3E5,2*this.xd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.xd+15E3*Math.random();g.ku(this.o,a);this.A=(0,g.G)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.xd=5E3};g.B(h7,MDa);g.h=h7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Xd=function(a){return this.B.Xd(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.jf(this.B),PDa(this),g.jf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.I="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new Z6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.wd=null);d.wd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.rk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.hc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):i7(this)&&GDa(this.o,c)};
g.h.Ky=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)GDa(this.o,a[b])}this.V("handlerOpened")};
g.h.Iy=function(a){var b=2==a&&401==this.o.Zf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.ds=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.Jz=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.hc(a,this.D);return a};
g.h.Jy=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),EDa(this.o)):this.V("handlerMessage",new NDa(a[0],a[1]))};
g.h.PX=function(){this.A.isActive();var a=this.o,b=0;a.yc&&b++;a.de&&b++;0!=b||this.connect(this.D,this.C)};j7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
j7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
j7.prototype.D=function(a){a(Error("request timed out"))};var XDa=(0,g.G)(),m7=null,p7=Array(50),o7=-1,q7=!1;g.B(r7,g.TF);r7.prototype.te=function(){return this.o};
r7.prototype.contains=function(a){return!!u6(this.o,a)};
r7.prototype.get=function(a){return a?v6(this.o,a):null};
r7.prototype.info=function(a){n7(this.G,a)};g.B(s7,g.TF);var eFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=s7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ea)&&this.lG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ea)||(g.jE(this.Ea),this.Ea=window.NaN)};
g.h.X=function(){this.stop();s7.ea.X.call(this)};
g.h.lG=function(){this.Ea=window.NaN;this.o=g.yE(k7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.RX,this),onError:(0,g.A)(this.QX,this),Cd:(0,g.A)(this.SX,this)})};
g.h.RX=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new p6(c))};
g.h.QX=function(a){this.o=null;a.status&&404==a.status?this.A>=eFa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=eFa[this.A],this.Ea=g.hE((0,g.A)(this.lG,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.SX=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(u7,r7);g.h=u7.prototype;g.h.start=function(){t7(this)&&this.V("screenChange");!g.cH("yt-remote-lounge-token-expiration")&&aEa(this);g.jE(this.A);this.A=g.hE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){t7(this);YDa(this,a);v7(this,!1);this.V("screenChange");b(a);a.token||aEa(this)};
g.h.remove=function(a,b){var c=t7(this);$Da(this,a)&&(v7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.ar=function(a,b,c,d){var e=t7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,v7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.jE(this.A);u7.ea.X.call(this)};
g.h.dL=function(a){t7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}v7(this,!b);b&&n7(this.G,"Missed "+b+" lounge tokens.")};
g.h.cL=function(a){n7(this.G,"Requesting lounge tokens failed: "+a)};g.B(x7,g.TF);g.h=x7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.cH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.G)()-144E5<a?0:a)?z7(this):(this.C=(0,g.G)()+3E5,g.bH("yt-remote-fast-check-period",this.C),this.Xv())};
g.h.isEmpty=function(){return g.$b(this.o)};
g.h.update=function(){w7("Updating availability on schedule.");var a=this.F(),b=g.Lb(this.o,function(b,d){return b&&!!v6(a,d)},this);
y7(this,b)};
g.h.X=function(){g.jE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);x7.ea.X.call(this)};
g.h.Xv=function(){g.jE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=dEa(this);if(g.Pb(a)){var b=k7(this.D,"/pairing/get_screen_availability");this.A=l7(this.D,b,{lounge_token:g.Sb(a).join(",")},(0,g.A)(this.RU,this,a),(0,g.A)(this.QU,this))}else y7(this,{}),z7(this)};
g.h.RU=function(a,b){this.A=null;var c=g.Sb(dEa(this));if(g.ib(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;y7(this,d);z7(this)}else this.hc("Changing Screen set during request."),this.Xv()};
g.h.QU=function(a){this.hc("Screen availability failed: "+a);this.A=null;z7(this)};
g.h.hc=function(a){n7("OnlineScreenService",a)};g.B(A7,r7);g.h=A7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.ar=function(a,b,c,d){this.B.contains(a)?this.B.ar(a,b,c,d):(a="Updating name of unknown screen: "+a.name,n7(this.G,a),d(Error(a)))};
g.h.te=function(a){return a?this.o:g.Xa(this.o,(0,g.Sd)(this.C,function(a){return!this.contains(a)},this))};
g.h.mG=function(){return(0,g.Sd)(this.te(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.nG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new s7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.jf(f);d(B7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.jf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.UX=function(a,b,c,d){g.yE(k7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new p6(d.screen||{});if(!e.name||hEa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);hEa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(B7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Cd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.jf(this.B);g.jf(this.A);A7.ea.X.call(this)};
g.h.sL=function(){iEa(this);this.V("screenChange");this.A.update()};
A7.prototype.dispose=A7.prototype.dispose;g.B(D7,g.TF);g.h=D7.prototype;g.h.eq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.ze=function(a){this.la()||(a&&E7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){n7(this.M,a)};
g.h.pG=function(){return null};
g.h.dw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){E7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.dw("");D7.ea.X.call(this)};g.B(F7,D7);g.h=F7.prototype;g.h.cw=function(a){if(this.o){if(this.o==a)return;E7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);kEa(this)};
g.h.tk=function(a){this.info("launchWithParams no-op for Cast: "+g.Hg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.ze()},this),(0,g.A)(function(){this.ze(Error("Failed to stop receiver app."))},this)):this.ze(Error("Stopping cast device witout session."))};
g.h.dw=g.z;g.h.X=function(){this.info("disposeInternal");g.jE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;F7.ea.X.call(this)};
g.h.VV=function(a,b){if(!this.la())if(b){var c=g.hx(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Hg(c));switch(d){case "mdxSessionStatus":jEa(this,c.screenId);break;default:E7(this,"Unknown youtube message: "+d)}}else E7(this,"Unable to parse message.")}else E7(this,"No data in message.")};
g.h.Tz=function(a,b,c,d){gEa(this.I,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(E7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.hE((0,g.A)(this.Tz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.pG=function(){return this.o};
g.h.VX=function(a){this.la()||a||(E7(this,"Cast session died."),this.ze())};g.B(G7,D7);g.h=G7.prototype;g.h.cw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.tk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.jE(this.F);this.C?this.C.stop((0,g.A)(this.ze,this,null),(0,g.A)(this.ze,this,"Failed to stop DIAL device.")):this.ze()};
g.h.X=function(){this.o();this.o=g.z;g.jE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;G7.ea.X.call(this)};
g.h.YX=function(a){this.la()||a||(E7(this,"DIAL session died."),this.o(),this.o=g.z,this.ze())};
g.h.Ut=function(a){this.K=t6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,mEa(this));a(b);lEa(this)}else this.G=(0,g.A)(function(){g.jE(this.F);this.G=g.z;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,mEa(this));a(b);lEa(this)},this),this.F=g.hE((0,g.A)(function(){this.G()},this),100)};
g.h.HM=function(a,b,c){gEa(this.I,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.eq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Ut(b,c)},this),(0,g.A)(function(a){E7(this,"Failed to get DIAL screen: "+a);
this.Ut(b,c)},this))};g.B(H7,D7);H7.prototype.stop=function(){this.ze()};
H7.prototype.cw=g.z;H7.prototype.tk=function(){g.jE(this.o);this.o=window.NaN;var a=v6(this.I.te(),this.A.label);a?this.eq(a):this.ze(Error("No such screen"))};
H7.prototype.X=function(){g.jE(this.o);this.o=window.NaN;H7.ea.X.call(this)};g.B(I7,g.TF);g.h=I7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.TD,this),(0,g.A)(this.AU,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.tS,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),UDa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.oG,this)),this.B=oEa(this),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.hc("Failed to set initial custom receivers: "+g.Hg(a))},this)),this.V("yt-remote-cast2-availability-change",K7(this)),b(!0))},this),(0,g.A)(function(a){this.hc("Failed to initialize API: "+g.Hg(a));
b(!1)},this))};
g.h.LW=function(a,b){J7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)J7("Unsetting old screen status: "+this.o.A.friendlyName),L7(this,null)}if(a&&b){if(!this.o){c=v6(this.A.te(),a);if(!c){J7("setConnectedScreenStatus: Unknown screen.");return}var d=nEa(this,c);d||(J7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.hc("Failed to set initial custom receivers: "+g.Hg(a))},this)));
J7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);L7(this,new H7(this.A,d),!0)}this.o.dw(b)}else J7("setConnectedScreenStatus: no screen.")};
g.h.NW=function(a){this.la()?this.hc("Setting connection data on disposed cast v2"):this.o?this.o.tk(a):this.hc("Setting connection data without a session")};
g.h.XX=function(){this.la()?this.hc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),L7(this,null)):J7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.TD,this),(0,g.A)(this.VU,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.oG,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ua(g.y("yt.mdx.remote.debug.handlers_")||[],RDa);g.jf(this.o);I7.ea.X.call(this)};
g.h.hc=function(a){n7("Controller",a)};
g.h.UD=function(a,b){this.o==a&&(b||L7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.wU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),J7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)J7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{J7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:L7(this,
new H7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:L7(this,new G7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:L7(this,new F7(this.A,a));break;default:this.hc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.hc("Stopping receiver w/o session: "+a.friendlyName)}else this.hc("onReceiverAction_ called without receiver.")};
g.h.tS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.hc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.hc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return J7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.hc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);L7(this,new G7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.HM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.Ut,b))};
g.h.TD=function(a){if(!this.la()){J7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)J7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),L7(this,new F7(this.A,b),!0);else{this.hc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=v6(this.A.te(),c.label);
d&&q6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(J7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.jf(this.o),this.o=new F7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.UD,this,this.o)),this.o.tk(null));this.o.cw(a)}}};
g.h.WX=function(){return this.o?this.o.pG():null};
g.h.VU=function(a){this.la()||(this.hc("Failed to estabilish a session: "+g.Hg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&L7(this,null))};
g.h.AU=function(a){J7("Receiver availability updated: "+a);if(!this.la()){var b=K7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;K7(this)!=b&&this.V("yt-remote-cast2-availability-change",K7(this))}};
g.h.oG=function(){this.la()||(this.B=oEa(this),J7("Updating custom receivers: "+g.Hg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.hc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",K7(this)))};
I7.prototype.setLaunchParams=I7.prototype.NW;I7.prototype.setConnectedScreenStatus=I7.prototype.LW;I7.prototype.stopSession=I7.prototype.XX;I7.prototype.getCastSession=I7.prototype.WX;I7.prototype.requestSession=I7.prototype.requestSession;I7.prototype.init=I7.prototype.init;I7.prototype.dispose=I7.prototype.dispose;var R7=[];g.h=W7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";X7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.eg=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.I=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.qb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.I+Y7(this):this.I};
g.h.clone=function(){return new W7(b8(this))};g.B(d8,g.TF);g.h=d8.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,j8(this,"play")):i8(this,"play"),h8(this,1,$7(e8(this))),this.V("remotePlayerChange")):f8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,j8(this,"pause")):i8(this,"pause"),h8(this,2,$7(e8(this))),this.V("remotePlayerChange")):f8(this,this.pause)};
g.h.kG=function(a){if(1==this.o){if(this.A){var b=e8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.qb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,j8(this,"seekTo",{newTime:a}))}else i8(this,"seekTo",{newTime:a});h8(this,3,a);this.V("remotePlayerChange")}else f8(this,g.Fa(this.kG,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,j8(this,"stopVideo")):i8(this,"stopVideo");var a=e8(this);a.index=-1;a.videoId="";X7(a);g8(this,a);this.V("remotePlayerChange")}else f8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=e8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){n7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){n7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);i8(this,"setVolume",e)}c.muted=b;c.volume=a;g8(this,c)}else f8(this,g.Fa(this.setVolume,a,b))};
g.h.lF=function(a,b){if(1==this.o){var c=e8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Hg(b.style),g.hc(d,c.A));i8(this,"setSubtitlesTrack",d);g8(this,c)}else f8(this,g.Fa(this.lF,a,b))};
g.h.Uw=function(a,b){if(1==this.o){i8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Jb.id});var c=e8(this);c.audioTrackId=b.Jb.id;g8(this,c)}else f8(this,g.Fa(this.Uw,a,b))};
g.h.jG=function(a,b){if(1==this.o){if(a&&b){var c=e8(this);a8(c,a,b);g8(this,c)}i8(this,"previous")}else f8(this,g.Fa(this.jG,a,b))};
g.h.iG=function(a,b){if(1==this.o){if(a&&b){var c=e8(this);a8(c,a,b);g8(this,c)}i8(this,"next")}else f8(this,g.Fa(this.iG,a,b))};
g.h.mz=function(){1==this.o?i8(this,"dismissAutoplay"):f8(this,this.mz)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}d8.ea.dispose.call(this)};
g.h.X=function(){BEa(this);this.C=null;this.D.clear();c8(this,null);d8.ea.X.call(this)};
g.h.Vw=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.AC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.rU=function(a,b){this.V(a,b)};
g.h.QR=function(a){if(!a)this.Om(null),c8(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=e8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)n7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,g8(this,b)}};
g.h.Om=function(a){n7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),CEa(this),this.V("remotePlayerChange")};
g.h.PR=function(a){a?(CEa(this),this.V("remotePlayerChange")):this.Om(null)};
g.h.cS=function(){var a=yEa();a&&c8(this,a)};
g.h.hc=function(a){n7("CP",a)};g.B(k8,g.TF);g.h=k8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.v(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.v(k)&&(l.currentIndex=k);c&&(this.ib.listId=c);this.ib.videoId=d;this.ib.index=k||0;this.ib.state=3;Z7(this.ib,m);this.C="UNSUPPORTED";l8("Connecting with setPlaylist and params: "+g.Hg(l));this.o.connect({method:"setPlaylist",
params:g.Hg(l)},a,YCa())}else l8("Connecting without params"),this.o.connect({},a,YCa());EEa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),m8(this,3));k8.ea.dispose.call(this)};
g.h.X=function(){n8(this);p8(this);o8(this);g.jE(this.I);this.I=window.NaN;g.jE(this.K);this.K=window.NaN;this.B=null;g.DF(this.T);this.T.length=0;this.o.dispose();k8.ea.X.call(this);this.C=this.G=this.A=this.ib=this.o=null};
g.h.UK=function(){this.F(2)};
g.h.UR=function(){l8("Channel opened");this.O&&(this.O=!1,o8(this),this.M=g.hE((0,g.A)(function(){l8("Timing out waiting for a screen.");this.F(1)},this),15E3));
bDa(ODa(this.o),this.ba)};
g.h.RR=function(){l8("Channel closed");(0,window.isNaN)(this.D)?A6(!0):A6();this.dispose()};
g.h.SR=function(a){A6();(0,window.isNaN)(this.H())?(l8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,l8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),m8(this,2))};
g.h.TR=function(a){a.params?l8("Received: action="+a.action+", params="+g.Hg(a.params)):l8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.hx(a.params.devices);this.A=(0,g.I)(a,function(a){return new o6(a)});
a=!!g.La(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
HEa(this,a);break;case "loungeScreenDisconnected":g.Wa(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
HEa(this,!1);break;case "remoteConnected":var b=new o6(g.hx(a.params.device));g.La(this.A,function(a){return b?a.id==b.id:!1})||g.Sa(this.A,b);
break;case "remoteDisconnected":b=new o6(g.hx(a.params.device));g.Wa(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":JEa(this,a);break;case "nowPlaying":LEa(this,a);break;case "onStateChange":KEa(this,a);break;case "onAdStateChange":MEa(this,a);break;case "onVolumeChanged":NEa(this,a);break;case "onSubtitlesTrackChanged":IEa(this,a);break;case "nowAutoplaying":OEa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":PEa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:l8("Unrecognized action: "+a.action)}};
g.h.vW=function(){if(this.B){var a=this.B;this.B=null;this.ib.videoId!=a&&q8(this,"getNowPlaying")}};
k8.prototype.subscribe=k8.prototype.subscribe;k8.prototype.unsubscribeByKey=k8.prototype.Xd;k8.prototype.ia=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?i7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
k8.prototype.getProxyState=k8.prototype.ia;k8.prototype.F=function(a){l8("Disconnecting with "+a);n8(this);this.V("beforeDisconnect",a);1==a&&A6();PDa(this.o,a);this.dispose()};
k8.prototype.disconnect=k8.prototype.F;k8.prototype.ga=function(){var a=this.ib;this.B&&(a=this.ib.clone(),a8(a,this.B,a.index));return b8(a)};
k8.prototype.getPlayerContextData=k8.prototype.ga;
k8.prototype.oa=function(a){var b=new W7(a);b.videoId&&b.videoId!=this.ib.videoId&&(this.B=b.videoId,g.jE(this.I),this.I=g.hE((0,g.A)(this.vW,this),5E3));var c=[];this.ib.listId==b.listId&&this.ib.videoId==b.videoId&&this.ib.index==b.index||c.push("remoteQueueChange");this.ib.o==b.o&&this.ib.volume==b.volume&&this.ib.muted==b.muted&&$7(this.ib)==$7(b)&&g.Hg(this.ib.A)==g.Hg(b.A)||c.push("remotePlayerChange");this.ib.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
k8.prototype.setPlayerContextData=k8.prototype.oa;k8.prototype.Z=function(){var a=this.o.F.id,b=g.La(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
k8.prototype.getOtherConnectedRemoteId=k8.prototype.Z;k8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.G)():window.NaN};
k8.prototype.getReconnectTimeout=k8.prototype.H;k8.prototype.aa=function(){return this.C||"UNSUPPORTED"};
k8.prototype.getAutoplayMode=k8.prototype.aa;k8.prototype.da=function(){return this.G||""};
k8.prototype.getAutoplayVideoId=k8.prototype.da;k8.prototype.va=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.lu(a.o);a.start()}};
k8.prototype.reconnect=k8.prototype.va;k8.prototype.ka=function(a,b){q8(this,a,b);GEa(this)};
k8.prototype.sendMessage=k8.prototype.ka;g.B(r8,r7);g.h=r8.prototype;g.h.te=function(a){return this.gd.$_gs(a)};
g.h.contains=function(a){return!!this.gd.$_c(a)};
g.h.get=function(a){return this.gd.$_g(a)};
g.h.start=function(){this.gd.$_st()};
g.h.add=function(a,b,c){this.gd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.gd.$_r(a,b,c)};
g.h.ar=function(a,b,c,d){this.gd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.gd.$_ubk(this.A[a]);this.A.length=0;this.gd=null;r8.ea.X.call(this)};
g.h.TX=function(){this.V("screenChange")};
g.h.QT=function(){this.V("onlineScreenChange")};
A7.prototype.$_st=A7.prototype.start;A7.prototype.$_gspc=A7.prototype.UX;A7.prototype.$_gsppc=A7.prototype.nG;A7.prototype.$_c=A7.prototype.contains;A7.prototype.$_g=A7.prototype.get;A7.prototype.$_a=A7.prototype.add;A7.prototype.$_un=A7.prototype.ar;A7.prototype.$_r=A7.prototype.remove;A7.prototype.$_gs=A7.prototype.te;A7.prototype.$_gos=A7.prototype.mG;A7.prototype.$_s=A7.prototype.subscribe;A7.prototype.$_ubk=A7.prototype.Xd;var s8=null,t8=null,I8=null,x8=[];g.t(J8,g.M);g.h=J8.prototype;
g.h.X=function(){g.M.prototype.X.call(this);this.C.stop();this.D.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.QD,this);this.o.unsubscribe("remotePlayerChange",this.Rm,this);this.o.unsubscribe("remoteQueueChange",this.fq,this);this.o.unsubscribe("autoplayUpNext",this.nD,this);this.o.unsubscribe("previousNextChange",this.ND,this);this.o.unsubscribe("nowAutoplaying",this.ED,this);this.o.unsubscribe("autoplayDismissed",this.mD,this);this.o=this.H=null};
g.h.mC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(M8(this)){if(!e8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":e8(this.o).qb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.ak(c[0],c[1]);break;case "control_subtitles_set_track":N8(this,c[0]);break;case "control_set_audio_track":c=c[0],M8(this)&&this.o.Uw(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();O8(this,0==c?void 0:c);break;case "control_seek":O8(this,c[0]);break;case "control_subtitles_set_track":N8(this,c[0]);break;case "control_set_audio_track":c=c[0],M8(this)&&this.o.Uw(this.A.getVideoData(1).videoId,c)}};
g.h.OR=function(a){this.L.PK(a)};
g.h.uX=function(a){this.mC("control_subtitles_set_track",g.$b(a)?null:a)};
g.h.AF=function(){var a=this.A.Cc("captions","track");g.$b(a)||N8(this,a)};
g.h.CD=function(a){if(M8(this)){this.o.unsubscribe("remotePlayerChange",this.Rm,this);var b=Math.round(a.volume);a=!!a.muted;var c=e8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Rm,this)}};
g.h.jT=function(){g.$b(this.F)||aFa(this,this.F);this.G=!1};
g.h.QD=function(a,b){this.D.stop();2==b&&this.xF()};
g.h.Rm=function(){if(M8(this)){this.C.stop();var a=e8(this.o);switch(a.o){case 1081:case 1:L8(this,new g.HP(8));this.wF();break;case 1085:case 3:L8(this,new g.HP(9));break;case 1083:case 0:L8(this,new g.HP(2));this.K.stop();K8(this,this.A.getVideoData().lengthSeconds);break;case 1084:L8(this,new g.HP(4));break;case 2:L8(this,new g.HP(4));K8(this,$7(a));break;case -1:L8(this,new g.HP(64));break;case -1E3:L8(this,new g.HP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=
e8(this.o).A;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,aFa(this,a));a=e8(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.WF()}else $Ea(this)};
g.h.ND=function(){this.A.V("mdxpreviousnextchange")};
g.h.fq=function(){M8(this)||$Ea(this)};
g.h.TJ=function(){this.o.mz()};
g.h.nD=function(a){a&&(a=g.yE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.vV,this)}))&&(this.O=(0,g.A)(a.abort,a))};
g.h.vV=function(a,b){var c=new g.CO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.ED=function(a){(0,window.isNaN)(a)||this.A.V("mdxnowautoplaying",a)};
g.h.mD=function(){this.A.V("mdxautoplaycanceled")};
g.h.OP=function(a,b){-1==e8(this.o).o?O8(this,a):b&&this.o.kG(a)};
g.h.WF=function(){if(M8(this)){var a=e8(this.o);this.B.Ha(this.T);a.muted?this.A.mute():this.A.ng();this.A.setVolume(a.volume);this.T=this.B.R(this.A,"onVolumeChange",this.CD)}};
g.h.wF=function(){this.C.stop();if(!this.o.la()){var a=e8(this.o);a.qb()&&L8(this,new g.HP(8));K8(this,$7(a));this.C.start()}};
g.h.xF=function(){this.D.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.D.start()};g.t(P8,g.W);P8.prototype.D=function(a){cFa(this,a.state)};g.t(Q8,g.eZ);Q8.prototype.L=function(){var a=this.A.Cc("remote","receivers");a&&1<a.length&&!this.A.Cc("remote","quickCast")?(this.I=g.lb(a,this.F,this),g.fZ(this,(0,g.I)(a,this.F)),a=this.A.Cc("remote","currentReceiver"),this.Df(this.F(a)),this.enable(!0)):this.enable(!1)};
Q8.prototype.F=function(a){return a.key};
Q8.prototype.Cf=function(a){return"cast-selector-receiver"==a?"Cast...":this.I[a].name};
Q8.prototype.Ad=function(a){g.eZ.prototype.Ad.call(this,a);this.A.Sd("remote","currentReceiver",this.I[a]);this.D.Sb()};g.t(R8,g.BU);g.h=R8.prototype;g.h.create=function(){UEa(g.FM(g.Y(this.o)));this.F.push(g.eG("yt-remote-before-disconnect",this.KR,this));this.F.push(g.eG("yt-remote-connection-change",this.BU,this));this.F.push(g.eG("yt-remote-receiver-availability-change",this.OD,this));this.F.push(g.eG("yt-remote-auto-connect",this.zU,this));this.F.push(g.eG("yt-remote-receiver-resumed",this.yU,this));this.OD()};
g.h.load=function(){this.o.Nu();g.BU.prototype.load.call(this);this.D=new J8(this,this.o,this.A);var a=(a=ZEa())?a.currentTime:0;var b=H8()?new d8(C8(),void 0):null;0==a&&b&&(a=$7(e8(b)));0!=a&&(this.I=a||0,this.o.V("progresssync",a,void 0));bFa(this,this.G,this.G);g.J_(this.o.app,6)};
g.h.unload=function(){this.o.V("mdxautoplaycanceled");this.C=this.B;g.kf(this.D,this.A);this.A=this.D=null;g.BU.prototype.unload.call(this);g.J_(this.o.app,5)};
g.h.X=function(){g.fG(this.F);g.BU.prototype.X.call(this)};
g.h.Hm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.D.mC.apply(this.D,[a].concat(g.oa(c)))};
g.h.KK=function(){return this.loaded?this.D.suggestion:null};
g.h.eg=function(){return this.A?e8(this.A).eg:!1};
g.h.hasNext=function(){return this.A?e8(this.A).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.CP=function(){var a=e8(this.A),b=this.o.getVideoData();return{allowSeeking:this.o.hd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+Y7(a):a.C,isPeggedToLive:1>=(a.F?a.B+Y7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+Y7(a):a.B,seekableStart:0<a.D?a.D+Y7(a):a.D}};
g.h.DP=function(){this.A&&this.A.iG()};
g.h.EP=function(){this.A&&this.A.jG()};
g.h.KR=function(a){1==a&&(this.K=this.A?e8(this.A):null)};
g.h.BU=function(){var a=H8()?new d8(C8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.A=a;this.K=null;b.key!=this.B.key&&(this.C=b,this.load())}else g.jf(this.A),this.A=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.o.getVideoData().videoId&&this.o.QB(a.videoId,$7(a)));this.o.V("videodatachange","newdata",this.o.getVideoData(),3)};
g.h.OD=function(){this.H=[this.B].concat(WEa());var a=D8()||this.B;S8(this,a);this.o.xa("onMdxReceiversChange")};
g.h.zU=function(){var a=D8();S8(this,a)};
g.h.yU=function(){this.C=D8()};
g.h.BP=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?U7():S8(this,b)),this.loaded?this.C:this.B;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&U7(),!0):!1}};
g.h.FP=function(){i8(this.A,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ec=function(){return!1};g.rX.remote=R8;})(_yt_player);
